### ISSUE TITLE
Morpheus endpoint deprecation

### ISSUE THREAD

**Issue by lukelloydagi** [tryfan/python-morpheus-cypher#1]
Morpheus docs (https://apidocs.morpheusdata.com/#cypher) state:

The endpoint **/api/cypher/v1** is now deprecated and will be removed in the future. The new endpoint is **/api/cypher**

**Comment by tryfan** [comment]
Thank for letting me know!

**Comment by tryfan** [comment]
Fixed in 0.1.2
