### ISSUE TITLE
option to set flag true to be used in subtenant

### ISSUE THREAD

**Issue by cuxtud** [tryfan/python-morpheus-cypher#4]
https://d.pr/i/5z1eUj by adding the true flag the cypher can be used with tasks whih are attached to workflow used in subtenants.

**Comment by lukelloydagi** [comment]
I thought I would drop a comment to say this is possible without using this Python module.

Use `<%=cypher.read('secret/myuserpassword')%>` as a command argument within your Morpheus task. Then within your Python code use `cypher = sys.argv[1]` which will have the value. It will call/use the **secret/myuserpassword** Cypher stored in the master tenant 👍
